import { Geist, Geist_Mono, Exo_2, Chivo, Telex } from "next/font/google";
import "./globals.css";
import { getUserData } from "./lib/api";
import Navbar from "./components/Navbar";
import UserProvider from "./components/UserProvider";
import { Toaster } from "sonner";
import { isAuthenticated } from "./lib/auth";
import * as Sentry from "@sentry/nextjs";

const exo2 = Exo_2({
    weight: "400",
    variable: "--font-exo2",
    subsets: ["latin"],
});

const chivo = Chivo({
    weight: "400",
    variable: "--font-chivo",
    subsets: ["latin"],
});
const telex = Telex({
    weight: "400",
    variable: "--font-telex",
    subsets: ["latin"],
});

export const metadata = {
    title: "NSH",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    Sentry.metrics.count("test_metric", 1);
    const data = (await isAuthenticated()) ? await getUserData() : null;
    //console.log(data);
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <link rel="icon" href="/NSH.ico" sizes="any" />
                {/* <meta property="og:image" content="<generated>" />
                <meta property="og:image:type" content="<generated>" />
                <meta property="og:image:width" content="<generated>" />
                <meta property="og:image:height" content="<generated>" />

                <meta name="twitter:image" content="<generated>" />
                <meta name="twitter:image:type" content="<generated>" />
                <meta name="twitter:image:width" content="<generated>" />
                <meta name="twitter:image:height" content="<generated>" /> */}
            </head>
            <body
                className={`${exo2.variable} ${chivo.variable} ${telex.variable}
                    antialiased scroll-smooth`}
            >
                <UserProvider value={{ data }}>
                    <Navbar />
                    {children}
                </UserProvider>
                <Toaster richColors closeButton position="top-left" />
            </body>
        </html>
    );
}
